package presentacion;

public enum Evento {
	/*--CUs de cada subs--*/
	
	//Factura
	ANYADIR_PASE_A_VENTA,
	QUITAR_PASE_DE_VENTA,
	CERRAR_VENTA, 
	BUSCAR_FACTURA,
	MOSTRAR_FACTURAS,
	MOSTRAR_FACTURAS_POR_CLIENTE,
	
	//Cliente
	ALTA_CLIENTE, 
	BUSCAR_CLIENTE, 
	BAJA_CLIENTE, 
	MOSTRAR_CLIENTES, 
	ACTUALIZAR_CLIENTE,
	ACTUALIZAR_CLIENTE_VIP,
	ACTUALIZAR_CLIENTE_NORMAL,
	
	//Pase
	ALTA_PASE,
	BAJA_PASE,
	BUSCAR_PASE,
	MOSTRAR_PASES,
	ACTUALIZAR_PASE_0,
	ACTUALIZAR_PASE_1,
	MOSTRAR_PASES_POR_OBRA,
	
	//Taquillero
	ALTA_TAQUILLERO,
	BAJA_TAQUILLERO,
	BUSCAR_TAQUILLERO,
	BUSCAR_DNI_TAQUILLERO,
	MOSTRAR_TAQUILLEROS,
	ACTUALIZAR_TAQUILLERO_0,
	ACTUALIZAR_TAQUILLERO_1,
	
	//Obra
	ALTA_OBRA,
	BAJA_OBRA,
	ACTUALIZAR_OBRA_0,
	ACTUALIZAR_OBRA_1,
	CONSULTAR_OBRA,
	BUSCAR_OBRA,
	MOSTRAR_OBRAS,
	
	//CompTea
	ALTA_COMPANIA_TEATRAL, 
	ACTUALIZAR_COMPANIA_TEATRAL_0,
	ACTUALIZAR_COMPANIA_TEATRAL_1,
	BUSCAR_COMPANIA_TEATRAL,
	BAJA_COMPANIA_TEATRAL, 
	MOSTRAR_COMPANIA_TEATRAL, 
	
	//MiemCompTea
	ACTUALIZAR_MIEMBRO_COMPANIA_0,
	ACTUALIZAR_MIEMBRO_COMPANIA_1,
	BUSCAR_MIEMBRO_COMPANIA,
	ALTA_MIEMBRO_COMPANIA,
	BAJA_MIEMBRO_COMPANIA,
	MOSTRAR_MIEMBROS_COMPANIA,

	
	/*--RESPUESTAS--*/
	RES_OK, //si
	RES_KO //no
}
