package presentacion;

public enum Evento {
	MAINWINDOW,
	/*--VENTANAS DE CU--*/
	
	//Factura
	ANYADIR_PASE_A_VENTA, 
	BUSCAR_FACTURA,
	CERRAR_VENTA, 
	MOSTRAR_FACTURAS, 
	QUITAR_PASE_DE_VENTA,
	
	
	//Cliente
	ALTA_CLIENTE, 
	BUSCAR_CLIENTE, 
	ELIMINAR_CLIENTE, 
	MOSTRAR_CLIENTE, 
	ACTUALIZAR_CLIENTE,
	
	
	//Pase
	
	CREAR_PASE,
	ELIMINAR_PASE,
	BUSCAR_PASE,
	LISTAR_PASES,
	ACTUALIZAR_PASE_CARGA,
	ACTUALIZAR_PASE_DESCARGA,
	MOSTRAR_PASES_POR_OBRA,
	
	//Taquillero
	
	
	//Obra
	CREAR_OBRA,
	ELIMINAR_OBRA,
	ACTUALIZAR_OBRA_0,
	ACTUALIZAR_OBRA_1,
	CONSULTAR_OBRA,
	BUSCAR_OBRA,
	MOSTRAR_OBRAS,
	
	//CompTea
	ALTA_COMPANIA_TEATRAL, 
	ACTUALIZAR_COMPANIA_TEATRAL,
	BUSCAR_COMPANIA_TEATRAL,
	ELIMINAR_COMPANIA_TEATRAL, 
	MOSTRAR_COMPANIA_TEATRAL, 
	
	//MiemCompTea
	ACTUALIZAR_MIEMBRO_COMPANIA,
	BUSCAR_MIEMBRO_COMPANIA,
	CONTRATAR_MIEMBRO_COMPANIA,
	DESPEDIR_MIEMBRO_COMPANIA,
	MOSTRAR_MIEMBROS_COMPANIA,

	
	/*--RESPUESTAS--*/
	RES_OK, 
	RES_KO,
}
